### PR TITLE
Issue #11 - Make the requireInject mocks argument optional

### PR DESCRIPTION
**Pull request by erikvold**

### CODE REVIEW

**Comment by erikvold** [comment]
@iarna mind taking a look at this for me?

**Comment by iarna** [comment]
@erikvold This patch would also need to update documentation too. But before you move on to that, can you tell me what problem calling `requireInject` w/o mocks is solving for you?

**Comment by erikvold** [comment]
> can you tell me what problem calling requireInject w/o mocks is solving for you?

@iarna Good call, maybe there is some better way to do this that I haven't figured out yet:

if some module `X` requires `Y`, where `Y` has some setup logic (like creating a db), and I want to wrap/replace single function exported by `Y`, like so:

```
var y = requireInject("y"); // setup logic is run, so internal variables are at initial state
let { doSomething } = y, counter = 0;
y.doSomething = (...args) => {
  counter++;
  return doSomething(...args)
};
var x = requireInject("x", { y });
```

**Comment by iarna** [comment]
And `requireInject` ensures that only your test gets your monkeypatched `y`. Gotcha.

With some docs, I'd be happy to take this.

**Comment by iarna** [comment]
Eh, I'd still like docs, but I also hate having PRs hanging out so I took this as is. =p It's in v1.4.2 as d39efea

**Pull request closed without merging**
